ansible_host: 10.118.10.23
disks:
- name: vda
if_list:
  - name: wan0
    ipv4:
      addr: 10.118.10.23
      mask: 24
      gw: 10.118.10.1
    mac: '52:54:00:12:34:59'
  - name: wan1
    ipv4:
      addr: 10.118.12.23
      mask: 24
    mac: '52:54:00:12:35:59'
fs_type: btrfs
btrfs_profile: single
arch: generic
datacenter: qemu
