---
- hosts: k8s
  tasks:
    - name: install packages
      portage:
        package:
          - app-emulation/containerd
          - app-emulation/cri-tools
          - net-firewall/conntrack-tools
          - net-firewall/ebtables
          - net-misc/socat
          - sys-apps/ethtool
          - sys-apps/dbus
          - sys-cluster/kubeadm
          - sys-cluster/kubelet
          - sys-cluster/kubectl
          - app-admin/helm
          - sys-cluster/keepalived
        state: present

    - name: remove manifest placeholder folder
      file:
        path: /etc/kubernetes/manifests
        state: absent
      ignore_errors: true

    - name: kubelet conf.d
      template:
        src: kubelet.confd
        dest: /etc/conf.d/kubelet

    - name: autoload modules
      copy:
        dest: /etc/conf.d/modules
        content: |
          modules="br_netfilter"

    - name: crictl config
      copy:
        dest: /etc/crictl.yaml
        content: |
          runtime-endpoint: unix:///run/containerd/containerd.sock
          image-endpoint: unix:///run/containerd/containerd.sock
          timeout: 10
          debug: false

    - name: sysctl forward
      lineinfile:
        path: /etc/sysctl.conf
        regexp: ^#?net.ipv4.ip_forward
        line: net.ipv4.ip_forward = 1

    - name: sysctl nolocal bind ipv4
      lineinfile:
        path: /etc/sysctl.conf
        regexp: ^#?net.ipv4.ip_nonlocal_bind
        line: net.ipv4.ip_nonlocal_bind = 1

    - name: sysctl nolocal bind ipv6
      lineinfile:
        path: /etc/sysctl.conf
        regexp: ^#?net.ipv6.ip_nonlocal_bind
        line: net.ipv6.ip_nonlocal_bind = 1

    - name: bpf fs
      lineinfile:
        path: /etc/fstab
        regexp: "/sys/fs/bpf"
        line: none  /sys/fs/bpf  bpf  rshared  0 0

    - name: vswitch routing table
      lineinfile:
        path: /etc/iproute2/rt_tables
        regexp: "^1 +vswitch"
        line: "1 vswitch"

    - name: keepalived config
      template:
        src: keepalived.conf
        dest: /etc/keepalived/keepalived.conf

    - name: vswitch default routes
      blockinfile:
        path: /etc/conf.d/net
        block: |
          # Additional routes for vswitch
          {% set iface = if_list[1] %}
          {% set iface_name = iface.name | replace('.', '_') %}
          routes_{{ iface_name }}="
          ${routes_{{ iface_name }}}
          {{ subnet_virt }}.0/24 dev {{ iface.name }}
          {{ subnet_virt }}.0/24 dev {{ iface.name }} table vswitch
          {{ subnet_lan }}.0/24 dev {{ iface.name }} table vswitch
          {% if vm_type == 'vbox' %}
          default dev {{ iface.name }} table vswitch
          {% else %}
          {{ subnet_ext }}.1 dev {{ iface.name }} table vswitch
          default via {{ subnet_ext }}.1 dev {{ iface.name }} table vswitch
          {% endif %}
          "
          rules_{{ iface_name }}="
          from all to 10.244.0.0/16 lookup main priority 200
          from {{ subnet_virt }}.0/24 table vswitch priority 201
          "

    - name: resolve machine name to it's default ip
      blockinfile:
        path: /etc/hosts
        block: |
          # Default machine ip
          {{ if_list[1].ipv4.addr }} {{ inventory_hostname }}

    - name: Containerd logrotate
      template:
        src: containerd.logrotate
        dest: '/etc/logrotate.d/containerd'

    - name: autostart containred
      service:
        name: containerd
        enabled: yes
        state: started
