---
- hosts: k8s
  vars:
    ansible_become: false
  tasks:
    - name: kubeadm helper folder
      file:
        path: "~/k8s/kubeadm"
        state: directory

    - name: kubeadm master helpers
      template:
        src: "helpers/{{ item }}"
        dest: "~/k8s/kubeadm/{{ item }}"
      with_items:
        - kube-setup.sh
        - kube-reset.sh
        - kubeadm.yml
      when: "inventory_hostname == 'k8s-1'"

    - name: kubeadm other helpers
      template:
        src: "helpers/{{ item }}"
        dest: "~/k8s/kubeadm/{{ item }}"
      with_items:
        - kube-postjoin.sh
        - kube-reset.sh
      when: "inventory_hostname != 'k8s-1'"

    - name: cilium helper folder
      file:
        path: "~/k8s/cilium"
        state: directory
      when: "inventory_hostname == 'k8s-1'"

    - name: cililum helper
      template:
        src: "helpers/{{ item }}"
        dest: "~/k8s/cilium/{{ item }}"
      with_items:
        - cilium-helm.sh
      when: "inventory_hostname == 'k8s-1'"
