---
- hosts: k8s
  gather_facts: no
  vars:
    ansible_become: false
  tasks:
    - name: start vms
      virt:
        name: "{{ inventory_hostname }}"
        state: running
      delegate_to: localhost
    - name: wait for vm to start
      wait_for:
        host: "{{ if_list[0].ipv4.addr }}"
        state: started
        port: 22
        delay: 30
        timeout: 300
      delegate_to: localhost
