---
- hosts: k8s
  gather_facts: no
  vars:
    ansible_become: false
  tasks:
    - name: start libvirt vms
      virt:
        name: "{{ inventory_hostname }}"
        state: running
      delegate_to: localhost
      when: "vm_type != 'vbox'"

    - name: start vbox vms
      shell: "VBoxManage startvm {{ inventory_hostname }}"
      delegate_to: localhost
      when: "vm_type == 'vbox'"

    - name: wait for vm to start
      wait_for:
        host: "{{ if_list[0].ipv4.addr }}"
        state: started
        port: 22
        delay: 30
        timeout: 600
      delegate_to: localhost
