---
- name: vm base
  import_playbook: vm-create.yml

- name: vm start
  import_playbook: vm-start.yml

- name: vm install
  import_playbook: vm-install.yml

- name: k8s install
  import_playbook: k8s-install.yml

- name: k8s helpers
  import_playbook: k8s-helpers.yml

- name: k8s patches
  import_playbook: k8s-patches.yml

- name: final reboot
  import_playbook: vm-reboot.yml
