# defaults
---
ansible_user: root

root: /mnt/gentoo

btrfs_compression: zstd

stage4_tarball: 'https://gentoo.{{ repo_domain }}/release/{{ arch }}/stage4-{{ arch }}-latest.tar.xz'

default_services:
  - level: sysinit
    services:
      - metalog
  - level: default
    services:
      - sshd
      - acpid
      - ntpd
      - ntp-client
